### ISSUE TITLE
Accent colors

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/meuikit#1]
# Hightlight colors
Highlight colors are an integral part of MeuiKit, and are used widely throughout Cyber, from the Dock to the Settings app.

# Accent colors
Accent colors are able to change the look and feel of the UI by allowing to pick a color from a ready palette of colors. Accent colors modify the highlight colors in order to suit the user's preference.

# MeuiKit
MeuiKit manages the overall look-and-feel of Cyber, so integrating accent colors into MeuiKit would be crucial.

This could be done through an accent color manager (already working on it!) and proper handling in the [settings daemon](https://github.com/cyberos/cyber-workspace).

**Comment by itsvic-dev** [comment]
Work in progress:
![image](https://user-images.githubusercontent.com/17727163/101990144-56e43980-3ca5-11eb-9d05-77dd27a7852c.png)

Preview of the red accent color (not functional yet):
![image](https://user-images.githubusercontent.com/17727163/101990289-67e17a80-3ca6-11eb-9cab-ee537ccd2b26.png)

**Comment by reionwong** [comment]
wow, looks great :+1:

**Comment by itsvic-dev** [comment]
works!
![image](https://user-images.githubusercontent.com/17727163/101991897-f8708880-3caf-11eb-9ff5-2bf7024e360d.png)

**Comment by itsvic-dev** [comment]
green
![image](https://user-images.githubusercontent.com/17727163/101992136-4934b100-3cb1-11eb-8617-b9951acd4fc6.png)

**Comment by itsvic-dev** [comment]
purple
![image](https://user-images.githubusercontent.com/17727163/101992487-f7415a80-3cb3-11eb-89a0-321e264ad307.png)

**Comment by itsvic-dev** [comment]
pink
![image](https://user-images.githubusercontent.com/17727163/101992575-b5fd7a80-3cb4-11eb-9992-6560e4a93b61.png)

**Comment by itsvic-dev** [comment]
Pushed accent colors to MeuiKit and Settings daemon, closing.
