### ISSUE TITLE
Snackbars (Toast)

### ISSUE THREAD

**Issue by zirnc** [cyberos/meuikit#12]
https://material-ui.com/zh/components/snackbars/

![image](https://user-images.githubusercontent.com/42088872/108579308-45807300-7361-11eb-8df9-fe0fa8ed852a.png)

**Comment by itsvic-dev** [comment]
Good idea. Definitely would be useful for stuff such as error messages.

**Comment by zirnc** [comment]
> Good idea. Definitely would be useful for stuff such as error messages.

Yes. Now in cyber-calculator I can’t think of a good way to prompt errors, so I hope to add this thing

**Comment by itsvic-dev** [comment]
@ChungZH @rekols 
![image](https://user-images.githubusercontent.com/17727163/108611912-ac467080-73e3-11eb-9570-834cf6de510c.png)
![image](https://user-images.githubusercontent.com/17727163/108611915-afd9f780-73e3-11eb-810a-69bbe416afe7.png)

(yes, it's possible to hide the close button)

**Comment by zirnc** [comment]
Love it :heart:

**Comment by itsvic-dev** [comment]
Current implementation, almost ready @ChungZH

It hides itself after 5 seconds, and is nicely animated.
https://user-images.githubusercontent.com/17727163/108612856-8bcee400-73ec-11eb-9a8c-8757f2d3d3b4.mp4

**Comment by itsvic-dev** [comment]
Here's my reference code:
https://cdn.discordapp.com/attachments/413430340388913171/812858751957729330/toast-test.qml

Creating a PR soon, let me know what you think.

**Comment by zirnc** [comment]
> Current implementation, almost ready @ChungZH
> 
> It hides itself after 5 seconds, and is nicely animated.
> [user-images.githubusercontent.com/17727163/108612856-8bcee400-73ec-11eb-9a8c-8757f2d3d3b4.mp4](https://user-images.githubusercontent.com/17727163/108612856-8bcee400-73ec-11eb-9a8c-8757f2d3d3b4.mp4)

The animation is really good

**Comment by reionwong** [comment]
I like it.

**Comment by KittyLe** [comment]
> Current implementation, almost ready @ChungZH
> 
> It hides itself after 5 seconds, and is nicely animated.
> https://user-images.githubusercontent.com/17727163/108612856-8bcee400-73ec-11eb-9a8c-8757f2d3d3b4.mp4

looks 🔥
