### ISSUE TITLE
Viewbackground color in light mode

### ISSUE THREAD

**Issue by reionwong** [cyberos/meuikit#3]
I don't think it looks good,  @omaemae  could you change back to the original color?  :)

**Comment by itsvic-dev** [comment]
Alright, I'll see what I can do to make it better.

**Comment by itsvic-dev** [comment]
![image](https://user-images.githubusercontent.com/17727163/102131863-20e4b800-3e53-11eb-8ce0-8c1fff17e149.png)

So far so good, though I will try to not make it too orange.

**Comment by itsvic-dev** [comment]
![image](https://user-images.githubusercontent.com/17727163/102132196-92246b00-3e53-11eb-831e-096c1ab7fc37.png)

Got it looking pretty nice, pushing.

**Comment by reionwong** [comment]
I think this color should not be so deep, because it is too different from the background color.
