### ISSUE TITLE
The new `Window` element has a few design issues.

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/meuikit#5]
I've started to port a few apps over to `MeuiKit.Window`, and I noticed that upon maximizing, the rounded corners at the bottom stay untouched, and the buttons at the top don't disappear. Looks like a bug to me.

![image](https://user-images.githubusercontent.com/17727163/103167324-827d2d00-482a-11eb-8407-450aeec46910.png)
![image](https://user-images.githubusercontent.com/17727163/103167327-8741e100-482a-11eb-835e-b780ebe538a8.png)

**Comment by reionwong** [comment]
https://github.com/cyberos/meuikit/commit/0e87f15735b367d40a473a565ce164599cbf7e9f

I have optimized it

**Comment by itsvic-dev** [comment]
Yup, that solves my concerns. Thanks!
