### ISSUE TITLE
Shadows for Meui.Window

### ISSUE THREAD

**Issue by itsvic-dev** [cyberos/meuikit#7]
Currently, Meui.Window doesn't contain any shadows, as opposed to its ApplicationWindow sibling.

Meui.Window:
![image](https://user-images.githubusercontent.com/17727163/104840109-a5e54600-58c5-11eb-8f38-20151ed9b65a.png)

ApplicationWindow (not really, but still uses the KWin border from the KWin plugins):
![image](https://user-images.githubusercontent.com/17727163/104840174-05435600-58c6-11eb-8152-c5a2dd11cda5.png)

From these screenshots (taken with Spectacle in active window mode), it's apparent that Meui.Window is lacking a shadow.

**Comment by itsvic-dev** [comment]
@Z-bin would you be willing to help out with this one?

**Comment by Z-bin** [comment]
> @Z-bin would you be willing to help out with this one?

OK, I haven't learned related qml knowledge before, and I will try my best to solve this problem outside of work.

**Comment by itsvic-dev** [comment]
Thank you! You might want to look into [DropShadow](https://doc.qt.io/qt-5/qml-qtgraphicaleffects-dropshadow.html), though I haven't found a way of making it work.

**Comment by itsvic-dev** [comment]
I don't think DropShadow will help us.

I used the following snippet to try and get a Meui.Window with a shadow:
```qml
import QtQuick 2.15
import QtQuick.Layouts 1.15
import QtQuick.Controls 1.4
import QtGraphicalEffects 1.12
import MeuiKit 1.0 as Meui
Item {
	Meui.Window {
		id: rootWindow
		width: 640
		height: 480
		content: Rectangle {
			Layout.fillWidth: true

			Label {
				anchors.centerIn: parent
				text: "Testing"
			}
		}
	}

	DropShadow {
		anchors.fill: rootWindow
		radius: 8.0
		samples: 17
		color: "black"
		source: rootWindow
	}
}
```
And after running with `qmlscene`...
```
$ qmlscene meuikitWindowShadowTesting.qml
WARNING: Cannot find style "meui-style" - fallback: "/usr/lib/qt/qml/QtQuick/Controls/Styles/Desktop"
file:///usr/lib/qt/qml/QtGraphicalEffects/GaussianBlur.qml:305:9: Unable to assign Window_QMLTYPE_10 to QQuickItem
file:///home/omame/Documents/cyber-work/testing/meuikitWindowShadowTesting.qml:22:3: Unable to assign Window_QMLTYPE_10 to QQuickItem
```
Ignoring the meui-style warning, it doesn't really work. I just get a "Testing" window without any shadow.
![image](https://user-images.githubusercontent.com/17727163/105472573-65f2da00-5c9c-11eb-8720-bb731e075821.png)

**Comment by itsvic-dev** [comment]
Any ideas? @rekols

**Comment by reionwong** [comment]
I think this should be the best way to achieve it?

```
The KWindowShadow class represents a drop-shadow that is drawn by the compositor. 
```

https://github.com/cyberos/cyber-qt-plugins/blob/main/widgetstyle/shadowhelper.cpp#L104

**Comment by itsvic-dev** [comment]
Now how are we going to put MeuiKit.Window into a QWidget? Possibly by assigining it in the libmeuikit library?

**Comment by reionwong** [comment]
I haven't tried it, but QQuickView inherits QWindow, I think they should be compatible :)

**Comment by itsvic-dev** [comment]
So this should be doable without much trouble, we just have to instantiate ShadowHelper and register Meui.Window, right?

**Comment by reionwong** [comment]
> So this should be doable without much trouble, we just have to instantiate ShadowHelper and register Meui.Window, right?

YUP

**Comment by itsvic-dev** [comment]
Now, how do we take this and register it in ShadowHelper anyway? https://github.com/cyberos/meuikit/blob/77583a058d59a7e883bffd0a4a9ba4a8165ec6a3/src/meuikit.cpp#L37

**Comment by itsvic-dev** [comment]
@rekols Any ideas for that?

**Comment by reionwong** [comment]
I think it needs to be refactored Window.qml I have time to finish it.

**Comment by itsvic-dev** [comment]
Thank you so much for helping!

**Comment by reionwong** [comment]
I've finished it!

https://github.com/cyberos/meuikit/commit/a692952d2677eeab834bb32f291614262ad56581
