### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by sonichy** [cyberos/meuikit#8]
1.`cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..`
Change to :
`cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .`

2.include could not find load file:
    ECMGenerateHeaders    
`sudo apt install extra-cmake-modules`

**Comment by itsvic-dev** [comment]
Please don't build in the root directory. **Always** build from a special `build` directory.

About ECM, I'm not sure Ubuntu 20.04 has the latest ECM.
